jupyter_book_task:
  env:
    JULIA_NUM_THREADS: auto
    JOBS: '4'
    GH_TOKEN: ENCRYPTED[!f19399b7d74f554de0824bc7349dc63626e4e6e5575daf3357c8b7cb1de56e5a0ceb0b71575f2dea3b4b366165f7aa60!]
  auto_cancellation: true
  container:
    dockerfile: .ci/Dockerfile
    cpu: 4
    memory: 16G
    use_in_memory_disk: true
  notebook_script: |
    parallel --joblog /tmp/log -j${JOBS} jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=1000 --execute --inplace {} ::: docs/*.ipynb
    cat /tmp/log
  build_script: |
    jupyter-book build docs --warningiserror --keep-going -v
  # Requires a `GH_TOKEN` PAT with repo scope access
  pages_script: |
    if [[ $CIRRUS_BRANCH == "main" ]]; then
      git remote set-url origin https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git
      ghp-import -n -p -f docs/_build/html
    fi
